services:
  php8.1:
    image: sineverba/php8xc:1.11.0
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh:ro
      - ~/.composer:/root/.composer
    working_dir: /var/www

  php8.2:
    image: sineverba/php8xc:1.15.0
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh:ro
      - ~/.composer:/root/.composer
    working_dir: /var/www

  php8.3:
    image: sineverba/php8xc:1.18.0
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh:ro
      - ~/.composer:/root/.composer
    working_dir: /var/www

  php:
    image: sineverba/php8xc:latest
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh:ro
      - ~/.composer:/root/.composer
    working_dir: /var/www